// <auto-generated />
using Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(ContextoBaseDatos))]
    [Migration("20260115031207_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Entidades.Estudiante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("Estudiantes", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Nota", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("idEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("idEstudiante");

                    b.Property<int>("idProfesor")
                        .HasColumnType("int")
                        .HasColumnName("idProfesor");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("id");

                    b.HasIndex("idEstudiante");

                    b.HasIndex("idProfesor");

                    b.ToTable("Notas", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Profesor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Nota", b =>
                {
                    b.HasOne("Dominio.Entidades.Estudiante", "estudiante")
                        .WithMany("notas")
                        .HasForeignKey("idEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Profesor", "profesor")
                        .WithMany("notas")
                        .HasForeignKey("idProfesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("estudiante");

                    b.Navigation("profesor");
                });

            modelBuilder.Entity("Dominio.Entidades.Estudiante", b =>
                {
                    b.Navigation("notas");
                });

            modelBuilder.Entity("Dominio.Entidades.Profesor", b =>
                {
                    b.Navigation("notas");
                });
#pragma warning restore 612, 618
        }
    }
}
